ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=5D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=3D0)

      DOUBLE PRECISION MDL_MH,MDL_MT,MDL_MW,MDL_MZ,MDL_MZP

      COMMON/MASSES/ MDL_MH,MDL_MT,MDL_MW,MDL_MZ,MDL_MZP


      DOUBLE PRECISION MDL_WH,MDL_WT,MDL_WW,MDL_WZ,MDL_WZP

      COMMON/WIDTHS/ MDL_WH,MDL_WT,MDL_WW,MDL_WZ,MDL_WZP


      DOUBLE COMPLEX GC_19, GC_20, GC_22, GC_23, GC_85, GC_86, GC_87,
     $  GC_88, GC_89, GC_90, GC_91, GC_93, GC_94, GC_95

      COMMON/COUPLINGS/ GC_19, GC_20, GC_22, GC_23, GC_85, GC_86,
     $  GC_87, GC_88, GC_89, GC_90, GC_91, GC_93, GC_94, GC_95

