ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_19 = ', GC_19
      WRITE(*,2) 'GC_20 = ', GC_20
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_85 = ', GC_85
      WRITE(*,2) 'GC_86 = ', GC_86
      WRITE(*,2) 'GC_87 = ', GC_87
      WRITE(*,2) 'GC_88 = ', GC_88
      WRITE(*,2) 'GC_89 = ', GC_89
      WRITE(*,2) 'GC_90 = ', GC_90
      WRITE(*,2) 'GC_91 = ', GC_91
      WRITE(*,2) 'GC_93 = ', GC_93
      WRITE(*,2) 'GC_94 = ', GC_94
      WRITE(*,2) 'GC_95 = ', GC_95
