ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cabi = ', MDL_CABI
      WRITE(*,*) 'mdl_gZp = ', MDL_GZP
      WRITE(*,*) 'mdl_zetaq33 = ', MDL_ZETAQ33
      WRITE(*,*) 'mdl_zetal33 = ', MDL_ZETAL33
      WRITE(*,*) 'mdl_zetaRu33 = ', MDL_ZETARU33
      WRITE(*,*) 'mdl_zetaRd33 = ', MDL_ZETARD33
      WRITE(*,*) 'mdl_zetaRe33 = ', MDL_ZETARE33
      WRITE(*,*) 'mdl_zetaqll = ', MDL_ZETAQLL
      WRITE(*,*) 'mdl_zetal22 = ', MDL_ZETAL22
      WRITE(*,*) 'mdl_zetal23 = ', MDL_ZETAL23
      WRITE(*,*) 'mdl_zetaRull = ', MDL_ZETARULL
      WRITE(*,*) 'mdl_zetaRdll = ', MDL_ZETARDLL
      WRITE(*,*) 'mdl_zetaRe22 = ', MDL_ZETARE22
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_MZp = ', MDL_MZP
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*) 'mdl_WZp = ', MDL_WZP
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cos__cabi = ', MDL_COS__CABI
      WRITE(*,*) 'mdl_CKM1x1 = ', MDL_CKM1X1
      WRITE(*,*) 'mdl_sin__cabi = ', MDL_SIN__CABI
      WRITE(*,*) 'mdl_CKM1x2 = ', MDL_CKM1X2
      WRITE(*,*) 'mdl_CKM1x3 = ', MDL_CKM1X3
      WRITE(*,*) 'mdl_CKM2x1 = ', MDL_CKM2X1
      WRITE(*,*) 'mdl_CKM2x2 = ', MDL_CKM2X2
      WRITE(*,*) 'mdl_CKM2x3 = ', MDL_CKM2X3
      WRITE(*,*) 'mdl_CKM3x1 = ', MDL_CKM3X1
      WRITE(*,*) 'mdl_CKM3x2 = ', MDL_CKM3X2
      WRITE(*,*) 'mdl_CKM3x3 = ', MDL_CKM3X3
      WRITE(*,*) 'mdl_newCKM1x1 = ', MDL_NEWCKM1X1
      WRITE(*,*) 'mdl_newCKM1x2 = ', MDL_NEWCKM1X2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_newCKM1x3 = ', MDL_NEWCKM1X3
      WRITE(*,*) 'mdl_newCKM2x1 = ', MDL_NEWCKM2X1
      WRITE(*,*) 'mdl_newCKM2x2 = ', MDL_NEWCKM2X2
      WRITE(*,*) 'mdl_newCKM2x3 = ', MDL_NEWCKM2X3
      WRITE(*,*) 'mdl_newCKM3x1 = ', MDL_NEWCKM3X1
      WRITE(*,*) 'mdl_newCKM3x2 = ', MDL_NEWCKM3X2
      WRITE(*,*) 'mdl_newCKM3x3 = ', MDL_NEWCKM3X3
      WRITE(*,*) 'mdl_zetal2x2 = ', MDL_ZETAL2X2
      WRITE(*,*) 'mdl_zetal2x3 = ', MDL_ZETAL2X3
      WRITE(*,*) 'mdl_zetal3x2 = ', MDL_ZETAL3X2
      WRITE(*,*) 'mdl_zetal3x3 = ', MDL_ZETAL3X3
      WRITE(*,*) 'mdl_zetaq1x1 = ', MDL_ZETAQ1X1
      WRITE(*,*) 'mdl_zetaq2x2 = ', MDL_ZETAQ2X2
      WRITE(*,*) 'mdl_zetaq3x3 = ', MDL_ZETAQ3X3
      WRITE(*,*) 'mdl_zetaRd1x1 = ', MDL_ZETARD1X1
      WRITE(*,*) 'mdl_zetaRd2x2 = ', MDL_ZETARD2X2
      WRITE(*,*) 'mdl_zetaRd3x3 = ', MDL_ZETARD3X3
      WRITE(*,*) 'mdl_zetaRe2x2 = ', MDL_ZETARE2X2
      WRITE(*,*) 'mdl_zetaRe3x3 = ', MDL_ZETARE3X3
      WRITE(*,*) 'mdl_zetaRu1x1 = ', MDL_ZETARU1X1
      WRITE(*,*) 'mdl_zetaRu2x2 = ', MDL_ZETARU2X2
      WRITE(*,*) 'mdl_zetaRu3x3 = ', MDL_ZETARU3X3
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_conjg__CKM3x1 = ', MDL_CONJG__CKM3X1
      WRITE(*,*) 'mdl_conjg__CKM3x2 = ', MDL_CONJG__CKM3X2
      WRITE(*,*) 'mdl_conjg__CKM3x3 = ', MDL_CONJG__CKM3X3
      WRITE(*,*) 'mdl_conjg__newCKM1x1 = ', MDL_CONJG__NEWCKM1X1
      WRITE(*,*) 'mdl_conjg__newCKM1x2 = ', MDL_CONJG__NEWCKM1X2
      WRITE(*,*) 'mdl_conjg__newCKM1x3 = ', MDL_CONJG__NEWCKM1X3
      WRITE(*,*) 'mdl_I5a11 = ', MDL_I5A11
      WRITE(*,*) 'mdl_conjg__newCKM2x1 = ', MDL_CONJG__NEWCKM2X1
      WRITE(*,*) 'mdl_conjg__newCKM2x2 = ', MDL_CONJG__NEWCKM2X2
      WRITE(*,*) 'mdl_conjg__newCKM2x3 = ', MDL_CONJG__NEWCKM2X3
      WRITE(*,*) 'mdl_I5a12 = ', MDL_I5A12
      WRITE(*,*) 'mdl_conjg__newCKM3x1 = ', MDL_CONJG__NEWCKM3X1
      WRITE(*,*) 'mdl_conjg__newCKM3x2 = ', MDL_CONJG__NEWCKM3X2
      WRITE(*,*) 'mdl_conjg__newCKM3x3 = ', MDL_CONJG__NEWCKM3X3
      WRITE(*,*) 'mdl_I5a13 = ', MDL_I5A13
      WRITE(*,*) 'mdl_I5a21 = ', MDL_I5A21
      WRITE(*,*) 'mdl_I5a22 = ', MDL_I5A22
      WRITE(*,*) 'mdl_I5a23 = ', MDL_I5A23
      WRITE(*,*) 'mdl_I5a31 = ', MDL_I5A31
      WRITE(*,*) 'mdl_I5a32 = ', MDL_I5A32
      WRITE(*,*) 'mdl_I5a33 = ', MDL_I5A33
      WRITE(*,*) 'mdl_sqrt__6 = ', MDL_SQRT__6
      WRITE(*,*) 'mdl_conjg__CKM1x1 = ', MDL_CONJG__CKM1X1
      WRITE(*,*) 'mdl_conjg__CKM1x2 = ', MDL_CONJG__CKM1X2
      WRITE(*,*) 'mdl_conjg__CKM1x3 = ', MDL_CONJG__CKM1X3
      WRITE(*,*) 'mdl_conjg__CKM2x1 = ', MDL_CONJG__CKM2X1
      WRITE(*,*) 'mdl_conjg__CKM2x2 = ', MDL_CONJG__CKM2X2
      WRITE(*,*) 'mdl_conjg__CKM2x3 = ', MDL_CONJG__CKM2X3
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_I2a13 = ', MDL_I2A13
      WRITE(*,*) 'mdl_I2a23 = ', MDL_I2A23
      WRITE(*,*) 'mdl_I2a33 = ', MDL_I2A33
      WRITE(*,*) 'mdl_I3a31 = ', MDL_I3A31
      WRITE(*,*) 'mdl_I3a32 = ', MDL_I3A32
      WRITE(*,*) 'mdl_I3a33 = ', MDL_I3A33
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
