C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (ProjM(2,1)) + Coup(2) * (ProjP(2,1))
C     
      SUBROUTINE FFS3_4L1_2(P1, S3, COUP1, COUP2, M2, W2, P2, COEFF)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 S3(*)
      COMPLEX*16 COUP2
      COMPLEX*16 P2(0:3)
      INCLUDE 'coef_specs.inc'
      COMPLEX*16 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      COMPLEX*16 P1(0:3)
      REAL*8 M2
      REAL*8 W2
      P2(0) = +P1(0)+S3(1)
      P2(1) = +P1(1)+S3(2)
      P2(2) = +P1(2)+S3(3)
      P2(3) = +P1(3)+S3(4)
      COEFF(1,0,1)= CI * M2*S3(5)*COUP1
      COEFF(2,0,1)= 0D0
      COEFF(3,0,1)= -COUP1*S3(5)*(+CI*(P2(0)+P2(3)))
      COEFF(4,0,1)= -COUP1*S3(5)*(+CI*(P2(1))-P2(2))
      COEFF(1,1,1)= 0D0
      COEFF(2,1,1)= 0D0
      COEFF(3,1,1)= -CI * S3(5)*COUP1
      COEFF(4,1,1)= 0D0
      COEFF(1,2,1)= 0D0
      COEFF(2,2,1)= 0D0
      COEFF(3,2,1)= 0D0
      COEFF(4,2,1)= -CI * S3(5)*COUP1
      COEFF(1,3,1)= 0D0
      COEFF(2,3,1)= 0D0
      COEFF(3,3,1)= 0D0
      COEFF(4,3,1)= S3(5)*COUP1
      COEFF(1,4,1)= 0D0
      COEFF(2,4,1)= 0D0
      COEFF(3,4,1)= -CI * S3(5)*COUP1
      COEFF(4,4,1)= 0D0
      COEFF(1,0,2)= 0D0
      COEFF(2,0,2)= CI * M2*S3(5)*COUP1
      COEFF(3,0,2)= -COUP1*S3(5)*(+CI*(P2(1))+P2(2))
      COEFF(4,0,2)= COUP1*S3(5)*(-CI*(P2(0))+CI*(P2(3)))
      COEFF(1,1,2)= 0D0
      COEFF(2,1,2)= 0D0
      COEFF(3,1,2)= 0D0
      COEFF(4,1,2)= -CI * S3(5)*COUP1
      COEFF(1,2,2)= 0D0
      COEFF(2,2,2)= 0D0
      COEFF(3,2,2)= -CI * S3(5)*COUP1
      COEFF(4,2,2)= 0D0
      COEFF(1,3,2)= 0D0
      COEFF(2,3,2)= 0D0
      COEFF(3,3,2)= -S3(5)*COUP1
      COEFF(4,3,2)= 0D0
      COEFF(1,4,2)= 0D0
      COEFF(2,4,2)= 0D0
      COEFF(3,4,2)= 0D0
      COEFF(4,4,2)= CI * S3(5)*COUP1
      COEFF(1,0,3)= COUP2*S3(5)*(-CI*(P2(0))+CI*(P2(3)))
      COEFF(2,0,3)= COUP2*S3(5)*(+CI*(P2(1))-P2(2))
      COEFF(3,0,3)= CI * M2*S3(5)*COUP2
      COEFF(4,0,3)= 0D0
      COEFF(1,1,3)= -CI * S3(5)*COUP2
      COEFF(2,1,3)= 0D0
      COEFF(3,1,3)= 0D0
      COEFF(4,1,3)= 0D0
      COEFF(1,2,3)= 0D0
      COEFF(2,2,3)= CI * S3(5)*COUP2
      COEFF(3,2,3)= 0D0
      COEFF(4,2,3)= 0D0
      COEFF(1,3,3)= 0D0
      COEFF(2,3,3)= -S3(5)*COUP2
      COEFF(3,3,3)= 0D0
      COEFF(4,3,3)= 0D0
      COEFF(1,4,3)= CI * S3(5)*COUP2
      COEFF(2,4,3)= 0D0
      COEFF(3,4,3)= 0D0
      COEFF(4,4,3)= 0D0
      COEFF(1,0,4)= COUP2*S3(5)*(+CI*(P2(1))+P2(2))
      COEFF(2,0,4)= -COUP2*S3(5)*(+CI*(P2(0)+P2(3)))
      COEFF(3,0,4)= 0D0
      COEFF(4,0,4)= CI * M2*S3(5)*COUP2
      COEFF(1,1,4)= 0D0
      COEFF(2,1,4)= -CI * S3(5)*COUP2
      COEFF(3,1,4)= 0D0
      COEFF(4,1,4)= 0D0
      COEFF(1,2,4)= CI * S3(5)*COUP2
      COEFF(2,2,4)= 0D0
      COEFF(3,2,4)= 0D0
      COEFF(4,2,4)= 0D0
      COEFF(1,3,4)= S3(5)*COUP2
      COEFF(2,3,4)= 0D0
      COEFF(3,3,4)= 0D0
      COEFF(4,3,4)= 0D0
      COEFF(1,4,4)= 0D0
      COEFF(2,4,4)= -CI * S3(5)*COUP2
      COEFF(3,4,4)= 0D0
      COEFF(4,4,4)= 0D0
      END


