ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_61 = ', GC_61
      WRITE(*,2) 'GC_62 = ', GC_62
      WRITE(*,2) 'GC_63 = ', GC_63
      WRITE(*,2) 'GC_64 = ', GC_64
      WRITE(*,2) 'GC_65 = ', GC_65
      WRITE(*,2) 'GC_66 = ', GC_66
