ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of Type-II_NLO_cba_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'R2GC_177_11 = ', R2GC_177_11
      WRITE(*,2) 'R2GC_177_12 = ', R2GC_177_12
      WRITE(*,2) 'GC_140 = ', GC_140
      WRITE(*,2) 'GC_141 = ', GC_141
      WRITE(*,2) 'GC_143 = ', GC_143
      WRITE(*,2) 'GC_146 = ', GC_146
      WRITE(*,2) 'GC_147 = ', GC_147
      WRITE(*,2) 'GC_149 = ', GC_149
