ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=2D0)

      DOUBLE PRECISION MDL_MB,MDL_MHA,MDL_MHH,MDL_MHL,MDL_MHP,MDL_MT
     $ ,MDL_MTA,MDL_MW,MDL_MZ

      COMMON/MASSES/ MDL_MB,MDL_MHA,MDL_MHH,MDL_MHL,MDL_MHP,MDL_MT
     $ ,MDL_MTA,MDL_MW,MDL_MZ


      DOUBLE PRECISION MDL_WHA,MDL_WHH,MDL_WHL,MDL_WHP,MDL_WT,MDL_WW
     $ ,MDL_WZ

      COMMON/WIDTHS/ MDL_WHA,MDL_WHH,MDL_WHL,MDL_WHP,MDL_WT,MDL_WW
     $ ,MDL_WZ


      DOUBLE COMPLEX GC_7, R2GC_177_11, R2GC_177_12, GC_140, GC_141,
     $  GC_143, GC_146, GC_147, GC_149

      COMMON/COUPLINGS/ GC_7, R2GC_177_11, R2GC_177_12, GC_140, GC_141
     $ , GC_143, GC_146, GC_147, GC_149

