ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      REAL*16 MP__G
      COMMON/MP_STRONG/ MP__G

      COMPLEX*32 MP__GAL(2)
      COMMON/MP_WEAK/ MP__GAL

      COMPLEX*32 MP__MU_R
      COMMON/MP_RSCALE/ MP__MU_R


      REAL*16 MP__MDL_MB,MP__MDL_MHA,MP__MDL_MHH,MP__MDL_MHL
     $ ,MP__MDL_MHP,MP__MDL_MT,MP__MDL_MTA,MP__MDL_MW,MP__MDL_MZ

      COMMON/MP_MASSES/ MP__MDL_MB,MP__MDL_MHA,MP__MDL_MHH,MP__MDL_MHL
     $ ,MP__MDL_MHP,MP__MDL_MT,MP__MDL_MTA,MP__MDL_MW,MP__MDL_MZ


      REAL*16 MP__MDL_WHA,MP__MDL_WHH,MP__MDL_WHL,MP__MDL_WHP
     $ ,MP__MDL_WT,MP__MDL_WW,MP__MDL_WZ

      COMMON/MP_WIDTHS/ MP__MDL_WHA,MP__MDL_WHH,MP__MDL_WHL
     $ ,MP__MDL_WHP,MP__MDL_WT,MP__MDL_WW,MP__MDL_WZ


      COMPLEX*32 MP__GC_7,MP__R2GC_177_11,MP__R2GC_177_12,MP__GC_140
     $ ,MP__GC_141,MP__GC_143,MP__GC_146,MP__GC_147,MP__GC_149

      COMMON/MP_COUPLINGS/ MP__GC_7,MP__R2GC_177_11,MP__R2GC_177_12
     $ ,MP__GC_140,MP__GC_141,MP__GC_143,MP__GC_146,MP__GC_147
     $ ,MP__GC_149


