ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      REAL*16 G
      COMMON/MP_STRONG/ G

      COMPLEX*32 GAL(2)
      COMMON/MP_WEAK/ GAL

      COMPLEX*32 MU_R
      COMMON/MP_RSCALE/ MU_R


      REAL*16 MDL_MB,MDL_MHA,MDL_MHH,MDL_MHL,MDL_MHP,MDL_MT,MDL_MTA
     $ ,MDL_MW,MDL_MZ

      COMMON/MP_MASSES/ MDL_MB,MDL_MHA,MDL_MHH,MDL_MHL,MDL_MHP,MDL_MT
     $ ,MDL_MTA,MDL_MW,MDL_MZ


      REAL*16 MDL_WHA,MDL_WHH,MDL_WHL,MDL_WHP,MDL_WT,MDL_WW,MDL_WZ

      COMMON/MP_WIDTHS/ MDL_WHA,MDL_WHH,MDL_WHL,MDL_WHP,MDL_WT,MDL_WW
     $ ,MDL_WZ


      COMPLEX*32 GC_7,R2GC_177_11,R2GC_177_12,GC_140,GC_141,GC_143
     $ ,GC_146,GC_147,GC_149

      COMMON/MP_COUPLINGS/ GC_7,R2GC_177_11,R2GC_177_12,GC_140,GC_141
     $ ,GC_143,GC_146,GC_147,GC_149


