ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'MU_R = ', MU_R
      WRITE(*,*) 'mdl_cabi = ', MDL_CABI
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_tb = ', MDL_TB
      WRITE(*,*) 'mdl_cba = ', MDL_CBA
      WRITE(*,*) 'mdl_m122 = ', MDL_M122
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MHL = ', MDL_MHL
      WRITE(*,*) 'mdl_MHH = ', MDL_MHH
      WRITE(*,*) 'mdl_MHA = ', MDL_MHA
      WRITE(*,*) 'mdl_MHp = ', MDL_MHP
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WHL = ', MDL_WHL
      WRITE(*,*) 'mdl_WHH = ', MDL_WHH
      WRITE(*,*) 'mdl_WHA = ', MDL_WHA
      WRITE(*,*) 'mdl_WHp = ', MDL_WHP
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_atan__tb = ', MDL_ATAN__TB
      WRITE(*,*) 'mdl_beta = ', MDL_BETA
      WRITE(*,*) 'mdl_cos__cabi = ', MDL_COS__CABI
      WRITE(*,*) 'mdl_CKM1x1 = ', MDL_CKM1X1
      WRITE(*,*) 'mdl_sin__cabi = ', MDL_SIN__CABI
      WRITE(*,*) 'mdl_CKM1x2 = ', MDL_CKM1X2
      WRITE(*,*) 'mdl_CKM2x1 = ', MDL_CKM2X1
      WRITE(*,*) 'mdl_CKM2x2 = ', MDL_CKM2X2
      WRITE(*,*) 'mdl_cba__exp__2 = ', MDL_CBA__EXP__2
      WRITE(*,*) 'mdl_sba = ', MDL_SBA
      WRITE(*,*) 'mdl_acos__cba = ', MDL_ACOS__CBA
      WRITE(*,*) 'mdl_alpha = ', MDL_ALPHA
      WRITE(*,*) 'mdl_cos__beta = ', MDL_COS__BETA
      WRITE(*,*) 'mdl_cb = ', MDL_CB
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_sin__beta = ', MDL_SIN__BETA
      WRITE(*,*) 'mdl_sb = ', MDL_SB
      WRITE(*,*) 'mdl_ca = ', MDL_CA
      WRITE(*,*) 'mdl_MHL__exp__2 = ', MDL_MHL__EXP__2
      WRITE(*,*) 'mdl_MHH__exp__2 = ', MDL_MHH__EXP__2
      WRITE(*,*) 'mdl_m112 = ', MDL_M112
      WRITE(*,*) 'mdl_m222 = ', MDL_M222
      WRITE(*,*) 'mdl_MM2 = ', MDL_MM2
      WRITE(*,*) 'mdl_sa = ', MDL_SA
      WRITE(*,*) 'mdl_cb__exp__3 = ', MDL_CB__EXP__3
      WRITE(*,*) 'mdl_sb__exp__3 = ', MDL_SB__EXP__3
      WRITE(*,*) 'mdl_MHp__exp__2 = ', MDL_MHP__EXP__2
      WRITE(*,*) 'mdl_MHA__exp__2 = ', MDL_MHA__EXP__2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_cb__exp__4 = ', MDL_CB__EXP__4
      WRITE(*,*) 'mdl_cba__exp__4 = ', MDL_CBA__EXP__4
      WRITE(*,*) 'mdl_cb__exp__2 = ', MDL_CB__EXP__2
      WRITE(*,*) 'mdl_sb__exp__2 = ', MDL_SB__EXP__2
      WRITE(*,*) 'mdl_sb__exp__4 = ', MDL_SB__EXP__4
      WRITE(*,*) 'mdl_cb__exp__5 = ', MDL_CB__EXP__5
      WRITE(*,*) 'mdl_cba__exp__3 = ', MDL_CBA__EXP__3
      WRITE(*,*) 'mdl_sb__exp__5 = ', MDL_SB__EXP__5
      WRITE(*,*) 'mdl_sba__exp__2 = ', MDL_SBA__EXP__2
      WRITE(*,*) 'mdl_sb__exp__6 = ', MDL_SB__EXP__6
      WRITE(*,*) 'mdl_sba__exp__3 = ', MDL_SBA__EXP__3
      WRITE(*,*) 'mdl_cb__exp__6 = ', MDL_CB__EXP__6
      WRITE(*,*) 'mdl_sba__exp__4 = ', MDL_SBA__EXP__4
      WRITE(*,*) 'mdl_cba__exp__6 = ', MDL_CBA__EXP__6
      WRITE(*,*) 'mdl_cba__exp__5 = ', MDL_CBA__EXP__5
      WRITE(*,*) 'mdl_sba__exp__5 = ', MDL_SBA__EXP__5
      WRITE(*,*) 'mdl_sba__exp__6 = ', MDL_SBA__EXP__6
      WRITE(*,*) 'mdl_conjg__CKM1x1 = ', MDL_CONJG__CKM1X1
      WRITE(*,*) 'mdl_conjg__CKM1x2 = ', MDL_CONJG__CKM1X2
      WRITE(*,*) 'mdl_conjg__CKM2x1 = ', MDL_CONJG__CKM2X1
      WRITE(*,*) 'mdl_conjg__CKM2x2 = ', MDL_CONJG__CKM2X2
      WRITE(*,*) 'mdl_MB__exp__2 = ', MDL_MB__EXP__2
      WRITE(*,*) 'mdl_MT__exp__2 = ', MDL_MT__EXP__2
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam1 = ', MDL_LAM1
      WRITE(*,*) 'mdl_lam2 = ', MDL_LAM2
      WRITE(*,*) 'mdl_lam3 = ', MDL_LAM3
      WRITE(*,*) 'mdl_lam4 = ', MDL_LAM4
      WRITE(*,*) 'mdl_lam5 = ', MDL_LAM5
      WRITE(*,*) 'mdl_vev1 = ', MDL_VEV1
      WRITE(*,*) 'mdl_vev2 = ', MDL_VEV2
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_I1a33 = ', MDL_I1A33
      WRITE(*,*) 'mdl_I2a33 = ', MDL_I2A33
      WRITE(*,*) 'mdl_I3a33 = ', MDL_I3A33
      WRITE(*,*) 'mdl_I4a33 = ', MDL_I4A33
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*) 'mdl_yb__exp__2 = ', MDL_YB__EXP__2
      WRITE(*,*) 'mdl_yt__exp__2 = ', MDL_YT__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
      WRITE(*,*) 'mdl_G__exp__3 = ', MDL_G__EXP__3
      WRITE(*,*) 'mdl_G__exp__4 = ', MDL_G__EXP__4
