ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_15 = ', GC_15
      WRITE(*,2) 'GC_16 = ', GC_16
      WRITE(*,2) 'GC_18 = ', GC_18
      WRITE(*,2) 'GC_19 = ', GC_19
