ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=5D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=3D0)

      DOUBLE PRECISION MDL_MH,MDL_MT,MDL_MVLQ,MDL_MW,MDL_MZ

      COMMON/MASSES/ MDL_MH,MDL_MT,MDL_MVLQ,MDL_MW,MDL_MZ


      DOUBLE PRECISION MDL_WH,MDL_WT,MDL_WVLQ,MDL_WW,MDL_WZ

      COMMON/WIDTHS/ MDL_WH,MDL_WT,MDL_WVLQ,MDL_WW,MDL_WZ


      DOUBLE COMPLEX GC_15, GC_16, GC_18, GC_19

      COMMON/COUPLINGS/ GC_15, GC_16, GC_18, GC_19

