ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cabi = ', MDL_CABI
      WRITE(*,*) 'mdl_gU = ', MDL_GU
      WRITE(*,*) 'mdl_betaL33 = ', MDL_BETAL33
      WRITE(*,*) 'mdl_betaRd33 = ', MDL_BETARD33
      WRITE(*,*) 'mdl_betaL23 = ', MDL_BETAL23
      WRITE(*,*) 'mdl_betaL32 = ', MDL_BETAL32
      WRITE(*,*) 'mdl_kappaU = ', MDL_KAPPAU
      WRITE(*,*) 'mdl_kappaUtilde = ', MDL_KAPPAUTILDE
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_MVLQ = ', MDL_MVLQ
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*) 'mdl_WVLQ = ', MDL_WVLQ
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cos__cabi = ', MDL_COS__CABI
      WRITE(*,*) 'mdl_CKM1x1 = ', MDL_CKM1X1
      WRITE(*,*) 'mdl_sin__cabi = ', MDL_SIN__CABI
      WRITE(*,*) 'mdl_CKM1x2 = ', MDL_CKM1X2
      WRITE(*,*) 'mdl_CKM1x3 = ', MDL_CKM1X3
      WRITE(*,*) 'mdl_CKM2x1 = ', MDL_CKM2X1
      WRITE(*,*) 'mdl_CKM2x2 = ', MDL_CKM2X2
      WRITE(*,*) 'mdl_CKM2x3 = ', MDL_CKM2X3
      WRITE(*,*) 'mdl_CKM3x1 = ', MDL_CKM3X1
      WRITE(*,*) 'mdl_CKM3x2 = ', MDL_CKM3X2
      WRITE(*,*) 'mdl_CKM3x3 = ', MDL_CKM3X3
      WRITE(*,*) 'mdl_newCKM1x1 = ', MDL_NEWCKM1X1
      WRITE(*,*) 'mdl_newCKM1x2 = ', MDL_NEWCKM1X2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_newCKM1x3 = ', MDL_NEWCKM1X3
      WRITE(*,*) 'mdl_newCKM2x1 = ', MDL_NEWCKM2X1
      WRITE(*,*) 'mdl_newCKM2x2 = ', MDL_NEWCKM2X2
      WRITE(*,*) 'mdl_newCKM2x3 = ', MDL_NEWCKM2X3
      WRITE(*,*) 'mdl_newCKM3x1 = ', MDL_NEWCKM3X1
      WRITE(*,*) 'mdl_newCKM3x2 = ', MDL_NEWCKM3X2
      WRITE(*,*) 'mdl_newCKM3x3 = ', MDL_NEWCKM3X3
      WRITE(*,*) 'mdl_betaL2x3 = ', MDL_BETAL2X3
      WRITE(*,*) 'mdl_betaL3x2 = ', MDL_BETAL3X2
      WRITE(*,*) 'mdl_betaL3x3 = ', MDL_BETAL3X3
      WRITE(*,*) 'mdl_betaRd3x3 = ', MDL_BETARD3X3
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_conjg__newCKM3x1 = ', MDL_CONJG__NEWCKM3X1
      WRITE(*,*) 'mdl_conjg__newCKM3x2 = ', MDL_CONJG__NEWCKM3X2
      WRITE(*,*) 'mdl_betaL1x3 = ', MDL_BETAL1X3
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_conjg__CKM3x1 = ', MDL_CONJG__CKM3X1
      WRITE(*,*) 'mdl_conjg__CKM3x2 = ', MDL_CONJG__CKM3X2
      WRITE(*,*) 'mdl_conjg__CKM3x3 = ', MDL_CONJG__CKM3X3
      WRITE(*,*) 'mdl_conjg__newCKM1x3 = ', MDL_CONJG__NEWCKM1X3
      WRITE(*,*) 'mdl_I5a21 = ', MDL_I5A21
      WRITE(*,*) 'mdl_conjg__newCKM2x3 = ', MDL_CONJG__NEWCKM2X3
      WRITE(*,*) 'mdl_I5a22 = ', MDL_I5A22
      WRITE(*,*) 'mdl_conjg__newCKM3x3 = ', MDL_CONJG__NEWCKM3X3
      WRITE(*,*) 'mdl_I5a23 = ', MDL_I5A23
      WRITE(*,*) 'mdl_conjg__newCKM1x1 = ', MDL_CONJG__NEWCKM1X1
      WRITE(*,*) 'mdl_conjg__newCKM1x2 = ', MDL_CONJG__NEWCKM1X2
      WRITE(*,*) 'mdl_I5a31 = ', MDL_I5A31
      WRITE(*,*) 'mdl_conjg__newCKM2x1 = ', MDL_CONJG__NEWCKM2X1
      WRITE(*,*) 'mdl_conjg__newCKM2x2 = ', MDL_CONJG__NEWCKM2X2
      WRITE(*,*) 'mdl_I5a32 = ', MDL_I5A32
      WRITE(*,*) 'mdl_I5a33 = ', MDL_I5A33
      WRITE(*,*) 'mdl_I6a12 = ', MDL_I6A12
      WRITE(*,*) 'mdl_I6a13 = ', MDL_I6A13
      WRITE(*,*) 'mdl_I6a22 = ', MDL_I6A22
      WRITE(*,*) 'mdl_I6a23 = ', MDL_I6A23
      WRITE(*,*) 'mdl_I6a32 = ', MDL_I6A32
      WRITE(*,*) 'mdl_I6a33 = ', MDL_I6A33
      WRITE(*,*) 'mdl_conjg__CKM1x1 = ', MDL_CONJG__CKM1X1
      WRITE(*,*) 'mdl_conjg__CKM1x2 = ', MDL_CONJG__CKM1X2
      WRITE(*,*) 'mdl_conjg__CKM1x3 = ', MDL_CONJG__CKM1X3
      WRITE(*,*) 'mdl_conjg__CKM2x1 = ', MDL_CONJG__CKM2X1
      WRITE(*,*) 'mdl_conjg__CKM2x2 = ', MDL_CONJG__CKM2X2
      WRITE(*,*) 'mdl_conjg__CKM2x3 = ', MDL_CONJG__CKM2X3
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_I2a13 = ', MDL_I2A13
      WRITE(*,*) 'mdl_I2a23 = ', MDL_I2A23
      WRITE(*,*) 'mdl_I2a33 = ', MDL_I2A33
      WRITE(*,*) 'mdl_I3a31 = ', MDL_I3A31
      WRITE(*,*) 'mdl_I3a32 = ', MDL_I3A32
      WRITE(*,*) 'mdl_I3a33 = ', MDL_I3A33
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
